---
- name: Install mainline Kernel
  block:
  - name: add mainline lts ppa
    command: |
      add-apt-repository -y ppa:tuxinvader/lts-mainline
    become: true

  - name: install kernel from ppa
    apt:
      name: "{{ packages }}"
      state: present
      force_apt_get: yes
      install_recommends: yes
    vars:
      packages:
      - linux-generic-5.15

- name: Install custom DHC tools
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    install_recommends: yes
  vars:
    packages:
    # we use xfs as our default filesystem
    - xfsprogs
    # a machine without a terminal multiplexer isn't a real machine
    - screen
    - tmux
    - mc
    # some well loved networking tools
    - inetutils-traceroute
    - tcptraceroute
    - arp-scan
    - nmap
    # as we love containers, we should have some low level container tools in place
    - cgroup-tools
    # some top-commands to make everyone in the team happy
    - htop
    - ctop
    - iotop
    - iftop
    # an instance without vim isn't an instance
    - vim
    # nfs-common is required to make the mount of nfs-shares possible
    - nfs-common

- name: disable apparmor
  systemd:
    name: apparmor
    enabled: no
    masked: yes

- name: disable rsyslog because we only need systemd-journald
  systemd:
    name: rsyslog
    enabled: no
    masked: yes

- name: disable apt-daily.timer
  systemd:
    name: apt-daily.timer
    enabled: no
    masked: yes

- name: disable apt-daily-upgrade.timer
  systemd:
    name: apt-daily-upgrade.timer
    enabled: no
    masked: yes

- name: disable motd-news.timer
  systemd:
    name: motd-news.timer
    enabled: no
    masked: yes

- name: disable motd-news.service
  systemd:
    name: motd-news.service
    enabled: no
    masked: yes

# fix rp_filter to value 1, otherwise calico won't work.
# see https://github.com/kubernetes-sigs/kind/issues/891
- name: fix rp_filter in /etc/sysctl.d/10-network-security.conf
  replace:
    path: /etc/sysctl.d/10-network-security.conf
    regexp: 'rp_filter=2'
    replace: 'rp_filter=1'

- name: disable apparmor
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=""'
    replace: 'GRUB_CMDLINE_LINUX="apparmor=0"'

- name: update grub config
  shell: update-grub

- name: Creates unit file directory
  file:
    path: /etc/systemd/system/ssh.service.d
    state: directory

- name: Create ssh boot order drop in file
  template:
    dest: /etc/systemd/system/ssh.service.d/boot-order.conf
    src: files/etc/systemd/system/ssh.service.d/boot-order.conf
