---
- name: Install custom DHC tools
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    install_recommends: yes
  vars:
    packages:
    - xfsprogs
    - etcd-client
    # - linux-generic-hwe-18.04

- name: disable apparmor
  systemd:
    name: apparmor
    enabled: no
    masked: yes

# fix rp_filter to value 1, otherwise calico won't work.
# see https://github.com/kubernetes-sigs/kind/issues/891
- name: fix rp_filter in /etc/sysctl.d/10-network-security.conf
  replace:
    path: /etc/sysctl.d/10-network-security.conf
    regexp: 'rp_filter=2'
    replace: 'rp_filter=1'

- name: disable rsyslog because we only need systemd-journald
  systemd:
    name: rsyslog
    enabled: no
    masked: yes

- name: disable apparmor
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=""'
    replace: 'GRUB_CMDLINE_LINUX="apparmor=0"'

- name: update grub config
  shell: update-grub

- name: Creates unit file directory
  file:
    path: /etc/systemd/system/ssh.service.d
    state: directory

- name: Create ssh boot order drop in file
  template:
    dest: /etc/systemd/system/ssh.service.d/boot-order.conf
    src: files/etc/systemd/system/ssh.service.d/boot-order.conf
