---
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: download containerd
  get_url:
    url: "{{ containerd_url }}"
    checksum: "sha256:{{ containerd_sha256 }}"
    dest: /opt/containerd.tar.gz
