name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Install prereqs
        run: ./.github/workflows/install-prereqs.sh
      - name: Execute packer
        run: ./.github/workflows/build.sh
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: true
      #     prerelease: true
      - name: upload qcow2
        uses: actions/upload-artifact@v1
        with:
          name: ubuntu-1910-${{ github.ref }}.qcow2
          path: ./images/capi/output/ubuntu-1910-kube-v1.17.3/ubuntu-1910-kube-v1.17.3.qcow2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload vmdk
        uses: actions/upload-artifact@v1
        with:
          name: ubuntu-1910-${{ github.ref }}.vmdk
          path: ./images/capi/output/ubuntu-1910-kube-v1.17.3/ubuntu-1910-kube-v1.17.3.vmdk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Upload qcow2
      #   id: upload-release-asset-qcow2
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./images/capi/output/ubuntu-1910-kube-v1.17.3/ubuntu-1910-kube-v1.17.3.qcow2
      #     asset_name: ubuntu-1910-kube-v1.17.3.qcow2
      #     asset_content_type: application/zip
      # - name: Upload vmdk
      #   id: upload-release-asset-vmdk
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./images/capi/output/ubuntu-1910-kube-v1.17.3/ubuntu-1910-kube-v1.17.3.vmdk
      #     asset_name: ubuntu-1910-kube-v1.17.3.vmdk
      #     asset_content_type: application/zip
